#!/bin/bash
## This will make a standalone application bundle with all needed QT4 libs included

# clean previous installs
rm -rf QAvimator.app/Contents/MacOS/qavimator
rm -rf QAvimator.app/Contents/Resources/Data
rm -rf QAvimator.app/Contents/Frameworks/Qt*

# build and install qavimator into the prepared app bundle
mkdir _build
cd _build
cmake ../../.. -DINSTALL_BIN=../QAvimator.app/Contents/MacOS -DINSTALL_DATA=../QAvimator.app/Contents/Resources -DCMAKE_OSX_ARCHITECTURES="ppc;i386" -DCMAKE_BUILD_TYPE=MinSizeRel
make install

# Fix linking and add required framework files to the project. This is optional if system QT4 frameworks should be used
cp -R /Library/Frameworks/QtCore.framework/Versions/4/QtCore ../QAvimator.app/Contents/Frameworks/
install_name_tool -id @executable_path/../Frameworks/QtCore ../QAvimator.app/Contents/Frameworks/QtCore
install_name_tool -change  QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore ../QAvimator.app/Contents/MacOS/qavimator

cp -R /Library/Frameworks/QtGui.framework/Versions/4/QtGui ../QAvimator.app/Contents/Frameworks/
install_name_tool -id @executable_path/../Frameworks/QtGui ../QAvimator.app/Contents/Frameworks/QtGui
install_name_tool -change  QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore ../QAvimator.app/Contents/Frameworks/QtGui
install_name_tool -change  QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui ../QAvimator.app/Contents/MacOS/qavimator

cp -R /Library/Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL ../QAvimator.app/Contents/Frameworks/
install_name_tool -id @executable_path/../Frameworks/QtOpenGL ../QAvimator.app/Contents/Frameworks/QtOpenGL
install_name_tool -change  QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore ../QAvimator.app/Contents/Frameworks/QtOpenGL
install_name_tool -change  QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui ../QAvimator.app/Contents/Frameworks//QtOpenGL
install_name_tool -change  QtOpenGL.framework/Versions/4/QtOpenGL @executable_path/../Frameworks/QtOpenGL ../QAvimator.app/Contents/MacOS/qavimator
